### ISSUE TITLE
OpenGL Error 1281 when used with Optifine (Optiforge)

### ISSUE THREAD

**Issue by jonaskohl** [LordGrimmauld/windowlogging#9]
Minecraft version: 1.16.5
Forge Version: 36.0.0
Optifine Version: 1.16.5 HD_U_G7_pre7
Windowlogging Version: mc1.16.3_v0.0.2
<details><summary>Relevant entry in `debug.log`</summary>
<pre>[15Feb2021 13:14:30.487] [Render thread/ERROR] [net.minecraft.client.renderer.GlDebugTextUtils/]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL14C.nglMultiDrawArrays(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL14C.glMultiDrawArrays(GL14C.java:153) [lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL14.glMultiDrawArrays(GL14.java:352) [lwjgl-opengl-3.2.2.jar:build 10]
	at com.mojang.blaze3d.platform.GlStateManager.glMultiDrawArrays(GlStateManager.java:2041) [?:?]
	at net.optifine.render.VboRegion.finishDraw(VboRegion.java:333) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.drawRegion(WorldRenderer.java:2327) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228441_a_(WorldRenderer.java:2245) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:2012) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.0.jar:36.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/31567969.call(Unknown Source) [forge-1.16.5-36.0.0.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]</pre></details>
OS: Windows 10 20H1
Java version: (Minecraft Built-In)

Happens on two different machines. Error only occurs after windowlogging any block

**Comment by LordGrimmauld** [comment]
Closing this as i can't make out any reason how windowlogging is conected to this or how i could fix it. If you have additional infos, you can reopen.
